### ISSUE TITLE
UI-UserLogin Page and forgot password 

### ISSUE THREAD

**Issue by anjumanjum** [serviceproviderpk/MadrassaWeb#1]
Nasir kindly work on **UI-UserLogin Page and forgot password, Remamber me etc** Screen and also  work on underline  Service  Repository

**Comment by serviceproviderpk** [comment]
I think login/forgot password kam frontend walay theme krain gay wo abhe decide nahi hova.

Db main 1 user create kr lo. uski value session main rakhwa lo or tables main save kr lo....


@anjumanjum  what is your suggesion?

**Comment by anjumanjum** [comment]
yar wo kal tk ye kam kr lain ne Kendo k right click wgraa Grid etc m mn kal final kr k dy don ga inko aik bar ap code review kr lnaa phr bs osi patern ko follow kr k chln gy agy.ye kam to krna hi krna h **Login ,forgot ,remember** etc 
agr koi kam kr rhy hn ksi project pe to than OK as u please

**Comment by serviceproviderpk** [comment]
Ok Fine. Goahead @NasirNiazkiyani  please

Thanks

**Comment by NasirNiazkiyani** [comment]
nwab bhai login and forogt pasword dono kal 4 bjhy tk ho jein gey...
jaldi ho jatey but ow kiya ha na ke kal sunday ha to kh ar kaam be hoatey hain;;;;...main khosish kariun ga jaldi ho jein

**Comment by serviceproviderpk** [comment]
I will suggest write  comments in english, it will improve our english (Suggestion only).
tuti puti english bhe chalay gi no issue

**Comment by anjumanjum** [comment]
Agreed Asif bhai 
Ok @NasirNiazkiyani

**Comment by NasirNiazkiyani** [comment]
@anjumanjum Login task is completed and code checked in..

and know iam working on forgot password task...


please take getlatest before work start...

**Comment by NasirNiazkiyani** [comment]
Forgot Password task done...

**Comment by AliRaza6600** [comment]
where is my task?what i do

**Comment by anjumanjum** [comment]
Validation  not working fine kind retest it.
