### ISSUE TITLE
latest Feedback Of MW (3/12/2016)

### ISSUE THREAD

**Issue by NasirNiazkiyani** [serviceproviderpk/MadrassaWeb#25]
1)Add Delete option on dashboard for all sections
2)Urdu Typings issue on dashboard  title field
3)Editor box for title field 
4)Articles images issues
5)progress bar on image and file uploading progress bar ob books and media files
6)create terms and conditions pages
7)inject google map on contact us page
8)on send news letter image sending option
9)Aap ki Raey Seprate link on on dashbaord

1) English Logo position try in one line (font change)
 with differtent style/position with out undeline
2) English/Urdu on top right
3) background bg of slide show
) on right side use some background color in section
  some color in items, change icon of bullet icon

1) menu font size (done)
 ) heading font size
 )  normal text font size (chart naqshajaat font is final) on http://localhost:5451/DarulFtaUrdu/Index/
 )  side bar section font should bhe same as font size of heading of naqshajaat
) on news detail show news of relevent category
) on home page side bar give title "Side Bar"
) on book tab  naey with nai
 on tab show latest 6 
 replace nahi malommat with " Taza Tareen Malomaat
) Add mahnama in main Menu and on right side bar
    Taqwa Books and Taqwa Mahnama show on differnt pages

**Comment by serviceproviderpk** [comment]
- Logo improvement
-Slide show template with out text in 3 colors


-Footer section title consistency
-Right side bar text verticle align center
-scrolling news shoulde be click able
 and on detail page show relevent news by category
rename خبریں   to Sidebar
-on home page  sections title padding top+bottom 3 pix
-home page side bar remove white bg
-on contact us page - on google map click show new window with google map url that i sent you.
-mahanama should be selected when its page is loaded
-article details menu should be selected
-on darul-taqwa-lectures accordion tab bg should be like as in right side
-remove font-size:14px from all inline styling
