### ISSUE TITLE
Final Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/MadrassaWeb#33]
1) Article Detail page Title: fontsize:
should be in center (Done)
2) http://darultaqwa.org/ContactUs/DarulTakwaContactUs/
not coming from db(Done)
3) http://darultaqwa.org/FeedBack/FeedbackForm/

only show form no neend to show  rabta detail etc.(Done)
4)http://darultaqwa.org/DarulFtaUrdu/Index/
search section formatting (Done)
5) http://darultaqwa.org/DarulFtaUrdu/DarulIftaIntroduction/

should show only description  (Done)
6) how to add fatwa without assignment steps
add new menu(Done)
"Fatwa Process"(Done)
"Fatwa Manuall" (inprogresss)
7)عمومی سوالات    ?? نئے اوراہم فتاوی how it  will be managed?(inprogresss)
8) on  photo detail page add button of "show in large size"(Done)
when it is clicked show image in new window(Done)
9) سبسکرائبرز کو جو میل بھیجتے ہیں اس میں(Done)

**Comment by serviceproviderpk** [comment]
10 remove this ![capture30](https://cloud.githubusercontent.com/assets/19146254/22279670/e3aa80ba-e2ed-11e6-8ef7-88c4f7df1c1c.PNG)

**Comment by Darultaqwa** [comment]
•	جب کوئی ’’شو  ان  لارج سائز‘‘ پر کلک کرے تو  امیج  اپنے اصل سائز میں کھلنا چاہئے۔ لیکن یہ بہت چھوٹا کھل رہا ہے۔ ویڈیو دیکھ لیں۔
https://drive.google.com/open?id=0B8EO9KURUqcbaENHMElhcVJhSWs

•	سبسکرائبرز کو جو میل بھیجتے ہیں اس میں پکچر نہیں جارہی  اور پہلے سے ٹیکسٹ بھی لکھا ہوا ہے۔جو ای میل بھیجی اور جو مجھے ملی دونوں کی تصویر یں دیکھ لیں۔
![sent mail](https://cloud.githubusercontent.com/assets/23413745/22537449/9237cec8-e92c-11e6-9f1b-bba1080001a0.PNG)

![received mail](https://cloud.githubusercontent.com/assets/23413745/22537454/9e0a4e6a-e92c-11e6-8d61-c4c31fa81060.PNG)

**Comment by Darultaqwa** [comment]
**ابھی یہ مسائل پیش آرہے ہیں۔**
•	سبسکرائبرز کو جواب میں  جو ای میل ملی اس میں 
1.	تصویر نہیں ہے حالانکہ تصویر ایڈ کی تھی۔
2.	ٹیکسٹ کی الائنمنٹ رائٹ نہیں  ہے حالانکہ رائٹ الائنمنٹ میں لکھا تھا۔
•	دارالافتاء کے موجودہ فتاوی کو  ایڈ کرنے کے لئے جگہ تو بن گئی ہے لیکن
1.	مینول فتوی ایڈ کرنے   کے لئے ’’مینج مینول فتوی‘‘ والے پیج میں(+)بٹن کام نہیں کررہا۔
2.	فتوی ایڈ کرنے کے لئے سوال پوچھنے والے کا نام سلیکٹ کرناضروری ہے حالانکہ موجودہ فتاوی کے سوال پوچھنے والوں کا نام ہمیں خود معلوم نہیں اور کوئی فرضی نام سلیکٹ کرنا بے فائدہ ہے۔اس لئے سوال پوچھنے والے کانام سلیکٹ کرنے کی آپشن نہیں ہونی چاہئے۔ 
3.	دارالافتاء مین پیج پر فتاوی کیٹیگری کی لسٹ کبھی خود بخود بار بار بند کھل ہوتی رہتی ہے۔
4.	فتوی ایڈ کرتے ہوئے کیٹیگری ’’عبادات‘‘ اور سب کیٹیگری ’’حج و عمرہ‘‘ سلیکٹ کی تھی لیکن فتوی ویب سائٹ پر ’’عمومی سوالات ‘‘اور’’نئے اور اہم فتاوی‘‘ والی سائیڈ بار میں  بھی نظر آرہا ہے حالانکہ نہ ’’عمومی سوالات ‘‘میں ایڈ کیا اور نہ’’ نئے اور اہم فتاوی‘‘ میں۔۔
5.	جو فتوی ویب سائٹ پر  نظر آرہا ہے اس فتوی میں ایک ہیڈنگ جو درمیان  میں رائٹ الائنمنٹ والی نظر آرہی ہے وہ نہیں ہونی چاہئے۔
6.	 اس فتوی میں ’’سوال‘‘ اور ’’جواب‘‘ کے لفظ کے بعد جو نشان (:) ہے وہ دائیں طرف چلا گیا ہے۔
7.	اس فتوی میں پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔ 
اس کی ویڈیو دیکھ لیں۔
https://drive.google.com/open?id=0B8EO9KURUqcbbG9EeUdQTEpBNE0

•	’’نئے اور اہم فتاوی ‘‘کو ایڈ کرنے کے لئے کوئی جگہ موجود نہیں ہے۔
•	عمومی سوالات میں ایک فتوی ایڈ کیا تو
1.	دہ فتوی ویب سائٹ پر ’’نئے اور اہم فتاوی ‘‘ میں بھی نظر آرہا ہے۔حالانکہ ’’نئے اور اہم فتاوی ‘‘ میں ایڈ نہیں کیا۔
2.	جو فتوی ویب سائٹ پر  نظر آرہا ہے اس فتوی میں ایک ہیڈنگ جو درمیان  میں رائٹ الائنمنٹ والی نظر آرہی ہے وہ نہیں ہونی چاہئے۔
3.	 اس فتوی میں ’’سوال‘‘ اور ’’جواب‘‘ کے لفظ کے بعد جو نشان (:) ہے وہ دائیں طرف چلا گیا ہے۔
4.	اس فتوی میں پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔ .
•	دارالافتاء و التحقیق کا تعارف لکھنے کے لئے
1.	اس فتوی میں ’’سوال‘‘ اور ’’جواب‘‘ کے لفظ کے بعد جو نشان (:) ہے وہ دائیں طرف چلا گیا ہے۔
2.	اس فتوی میں پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔ 
3.	نمبرز بائیں طرف چلے جاتے ہیں۔

**Comment by NasirNiazkiyani** [comment]
بھی یہ مسائل پیش آرہے ہیں۔
•	سبسکرائبرز کو جواب میں جو ای میل ملی اس میں

تصویر نہیں ہے حالانکہ تصویر ایڈ کی تھی۔
ٹیکسٹ کی الائنمنٹ رائٹ نہیں ہے حالانکہ رائٹ الائنمنٹ میں لکھا تھا۔
•	دارالافتاء کے موجودہ فتاوی کو ایڈ کرنے کے لئے جگہ تو بن گئی ہے لیکن

دارالافتاء مین پیج پر فتاوی کیٹیگری کی لسٹ کبھی خود بخود بار بار بند کھل ہوتی رہتی ہے۔
فتوی ایڈ کرتے ہوئے کیٹیگری ’’عبادات‘‘ اور سب کیٹیگری ’’حج و عمرہ‘‘ سلیکٹ کی تھی لیکن فتوی ویب سائٹ پر ’’عمومی سوالات ‘‘اور’’نئے اور اہم فتاوی‘‘ والی سائیڈ بار میں بھی نظر آرہا ہے حالانکہ نہ ’’عمومی سوالات ‘‘میں ایڈ کیا اور نہ’’ نئے اور اہم فتاوی‘‘ میں۔۔


دہ فتوی ویب سائٹ پر ’’نئے اور اہم فتاوی ‘‘ میں بھی نظر آرہا ہے۔حالانکہ ’’نئے اور اہم فتاوی ‘‘ میں ایڈ نہیں کیا۔
جو فتوی ویب سائٹ پر نظر آرہا ہے اس فتوی میں ایک ہیڈنگ جو درمیان میں رائٹ الائنمنٹ والی نظر آرہی ہے وہ نہیں ہونی چاہئے۔

اس فتوی میں ’’سوال‘‘ اور ’’جواب‘‘ کے لفظ کے بعد جو نشان (:) ہے وہ دائیں طرف چلا گیا ہے۔
اس فتوی میں پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔
نمبرز بائیں طرف چلے جاتے ہیں۔

•	



•	فوٹو گیلری کا پیج جامعہ کی تصاویر لگانے کے لئے ہے ۔مضمون کی تصویر فوٹو گیلری میں نہیں دے سکتے۔ مضمون میں تصویر لگانے کا کوئی اور طریقہ بتادیجئے۔


لائن کے درمیان میں کہیں بھی انگلش کا لفظ ہو تو پوری لائن کی ترتیب خراب ہوجاتی ہے۔

**Comment by NasirNiazkiyani** [comment]
بھی یہ مسائل پیش آرہے ہیں۔
•	سبسکرائبرز کو جواب میں جو ای میل ملی اس میں(pending)

تصویر نہیں ہے حالانکہ تصویر ایڈ کی تھی۔(pending)
ٹیکسٹ کی الائنمنٹ رائٹ نہیں ہے حالانکہ رائٹ الائنمنٹ میں لکھا تھا۔(pending)
•	دارالافتاء کے موجودہ فتاوی کو ایڈ کرنے کے لئے جگہ تو بن گئی ہے لیکن(pending)



دہ فتوی ویب سائٹ پر ’’نئے اور اہم فتاوی ‘‘ میں بھی نظر آرہا ہے۔حالانکہ ’’نئے اور اہم فتاوی ‘‘ میں ایڈ نہیں کیا۔(pending)
جو فتوی ویب سائٹ پر نظر آرہا ہے اس فتوی میں ایک ہیڈنگ جو درمیان میں رائٹ الائنمنٹ والی نظر آرہی ہے وہ نہیں ہونی چاہئے۔
(pending)
اس فتوی میں ’’سوال‘‘ اور ’’جواب‘‘ کے لفظ کے بعد جو نشان (:) ہے وہ دائیں طرف چلا گیا ہے۔
اس فتوی میں پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔
**(Fixed)**نمبرز بائیں طرف چلے جاتے ہیں۔

•	


(pending)
•	فوٹو گیلری کا پیج جامعہ کی تصاویر لگانے کے لئے ہے ۔مضمون کی تصویر فوٹو گیلری میں نہیں دے سکتے۔ مضمون میں تصویر لگانے کا کوئی اور طریقہ بتادیجئے۔

(pending)
لائن کے درمیان میں کہیں بھی انگلش کا لفظ ہو تو پوری لائن کی ترتیب خراب ہوجاتی ہے۔

**Comment by Darultaqwa** [comment]
**ناصر بھائی کے ۹ فروری والے کمنٹ کی ٹیسٹنگ کی ہے۔ یہ مسائل ابھی بھی پیش آرہے ہیں۔**

1. سبسکرائبرز کو ای میل میں مائکروسافٹ ورڈ سے کاپی کرکے تصویر بھی بھیجی ہے۔ لیکن جب ای میل ملی تو اس میں تصویر کی بجائے کوڈ لکھا ہوا ہے۔ اس کی ویڈیو دیکھ لیں۔
https://drive.google.com/open?id=0B8EO9KURUqcbMlRUUXY2TWVwZUU 

2.  ایک فتوی ’’لا پتہ شوہر نکاح ثانی کے بعد واپس آگیا‘‘ کیٹیگری ’’خاندانی معملات‘‘ اور سب کیٹیگری ’’فسخ نکاح‘‘ میں ایڈ کیا ہے۔ وہ فتوی ابھی تک اس سب کیٹیگری میں تو نظر نہیں آرہا لیکن ’’دارالافتاء و التحقیق کا تعارف‘‘ والے پیج میں سائیڈ بار ’’نئے اور اہم فتاوی‘‘ میں نظر أرہا ہے۔ اور وہاں پر اسکا ٹیکسٹ صحیح ہے۔
یعنی فتوی جس طرح نظر آنا چاہئے ویسے ہی نظر آرہا ہے لیکن ویب سائٹ پر اپنی جگہ کی بجائے کہیں اور  جگہ پر نظر آرہا ہے۔ ویڈیو دیکھ لیں۔
https://drive.google.com/open?id=0B8EO9KURUqcbNlN3ekV0U21BZVE 

4. آپکا سوال پیج میں ایک لائن کے درمیان میں انگلش کا لفظ ہے۔ اس سے پہلے بریکٹ بھی لگائی ہے لیکن ترتیب پھر بھی خراب ہوگئی ہے۔ ویڈیو دیکھ لیں۔
https://drive.google.com/open?id=0B8EO9KURUqcbQ2sxYy1xSXpWNUk 

**اگر ناصر بھائی کے 9 فروری والے کمنٹ کے علاوہ اور کوئی کام ہوگیا ہے تو مجھے بتادیں تاکہ میں ٹیسٹنگ کرلوں۔**

**Comment by serviceproviderpk** [comment]
1)Subhaan bhai, Pehaly ap image ko uplaod krain http://darultaqwa.org/ManagePhotoGallery/SystemPhoto main ja kr
 phir isko add kr dain.
2) Fixed
3) Fixed.
