### ISSUE TITLE
Feedback 30jan2017

### ISSUE THREAD

**Issue by NasirNiazkiyani** [serviceproviderpk/MadrassaWeb#34]
(Done)·       ایڈمن سیکشن سے News   کو edit  کرنے کے لئے جو پیج ہے وہ blank نظر آرہا ہے۔

·       ویب سائٹ کے فوٹر میں  جو سوشل میڈیا   آئکنز ہیں ان سے جامعہ کا فیس بک پیج کیسے کھلے گا؟ جامعہ کے (Done)فیس بک پیج کا ایڈریس www.facebook.com/jamiadarultaqwa

·       جامعہ کا تعارف   لکھنے کے لئے
(Done)
(Done)1.     پیراگراف کے شروع میں خالی جگہ ابھی بھی نہیں آرہی۔

(Done)2.     پیراگراف کے شروع میں جو نمبر لکھا ہوا ہے وہ لائن کے بائیں طرف چلا جاتا ہے۔

(Done)3.     فونٹ کا سائز بڑا کرنے کی آپشن موجود نہیں ہے۔

·       فوٹو گیلری کا پیج جامعہ کی تصاویر لگانے کے لئے ہے ۔مضمون کی تصویر فوٹو گیلری میں نہیں دے سکتے۔ (pending)مضمون میں تصویر لگانے کا کوئی اور طریقہ بتادیجئے۔

·       (Done)طریقہ تعاون لکھنے کے لئے

(Done)1.     پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔

(Done)2.     فونٹ بدلنے کی آپشن موجود نہیں ہے۔

(Done)3.     نمبرز بائیں طرف چلے جاتے ہیں۔

·      (Done) تخصص فی الفقہ کی تفصیل لکھنے کے لئے

(Done)1.     پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔

(Done)2.     ہیڈنگ کے آگے جو نشان(:) ہے وہ دائیں طرف چلا جاتا ہے۔

(Done)3.     فونٹ سائز بڑا کرنے کی آپشن موجود نہیں ہے۔

(Done)4.     ٹیبل Paste نہیں ہوتا۔

(Done)5.     فونٹ بدلنے کی آپشن نہیں ہے۔

(Done)6.     نمبرز بائیں طرف چلے جاتے ہیں۔

·       ’’آپکا سوال‘‘ پیج میں جو ہدایات لکھی ہوئی ہیں ان کو edit  کرنے کے لئے  ایڈمن سیکشن میں کوئی جگہ موجود (Done)نہیں ہے۔

·   (sir ye heading alrady db se display ho rei ha)    مضامین کے اوپر ہیڈنگ آپ نہ لکھیں وہ ہم خود لکھ لیں گے۔

**Comment by Darultaqwa** [comment]
•	جامعہ کا تعارف، طریقہ تعاون، تخصص فی الفقہ کی تفصیل لکھنے میں جو جو مسائل میں نے بتائے تھے وہ ویب سائٹ پر ابھی بھی ویسے ہی پیش آرہے  ہیں۔ ایڈمن سیکشن میں وہ مسائل حل ہوگئے ہیں۔ ان تینوں پیجز کی الگ الگ ویڈیو ز بنادی ہیں۔ درج ذیل لنک کھول کر دیکھ لیں۔
https://drive.google.com/open?id=0B8EO9KURUqcbY2EzRDFVRk9Zbms 

https://drive.google.com/open?id=0B8EO9KURUqcbNkc2U192OG5yemM

https://drive.google.com/open?id=0B8EO9KURUqcbRG0td2FnLW9SUW8

•	ایڈمن سیکشن میں آپکا سوال والے پیج کے اندر ہدایات ایڈٹ  کرنے کے لئے جگہ تو اب بن گئی ہے لیکن ہدایات لکھنے میں بھی پیراگراف کے شروع میں خالی جگہ نہ ہونے اور نمبرز بائیں طرف چلے جانے جیسے مسائل پیش آرہے ہیں۔ 

•	مضامین اور فقہی  مضامین   میں  دو دو ہیڈنگز نظر آرہی ہیں ۔ بڑی والی ہیڈنگ جو نیچے ہے وہ میں نے خود لکھی ہے اس کے اوپر جو ہیڈنگ نظر آرہی ہے وہ نہیں ہونی چاہئے۔اس کی تصویریں دیکھ لیں۔
![article](https://cloud.githubusercontent.com/assets/23413745/22496727/1e9d841c-e86e-11e6-8a69-1be3003086d3.PNG)
![fiqhi article](https://cloud.githubusercontent.com/assets/23413745/22496737/2f956e06-e86e-11e6-960b-8e168f0498fb.PNG)

**Comment by Darultaqwa** [comment]
نمبر 34 میں ابھی درج ذیل کام نہیں ہوئے۔
•	جامعہ کا تعارف   لکھنے کے لئے
1.	پیراگراف کے شروع میں خالی جگہ ابھی بھی نہیں آرہی۔
2.	پیراگراف کے شروع میں جو نمبر لکھا ہوا ہے وہ لائن کے بائیں طرف چلا جاتا ہے۔
•	فوٹو گیلری کا پیج جامعہ کی تصاویر لگانے کے لئے ہے ۔مضمون کی تصویر فوٹو گیلری میں نہیں دے سکتے۔ مضمون میں تصویر لگانے کا کوئی اور طریقہ بتادیجئے۔
•	طریقہ تعاون لکھنے کے لئے 
1.	پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔
2.	نمبرز بائیں طرف چلے جاتے ہیں۔
•	تخصص فی الفقہ کی تفصیل لکھنے کے لئے 
1.	پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔
2.	ہیڈنگ کے آگے جو نشان(:) ہے وہ دائیں طرف چلا جاتا ہے۔
3.	ٹیبل پیسٹ نہیں ہوتا۔
4.	نمبرز بائیں طرف چلے جاتے ہیں۔
•	’’آپکا سوال‘‘ پیج میں ہدایات لکھنے کے لئے    
1.	پیراگراف کے شروع میں خالی جگہ نہیں آرہی۔
2.	نمبرز بائیں طرف چلے جاتے ہیں۔
3.	لائن کے درمیان میں کہیں بھی انگلش کا لفظ ہو تو پوری لائن کی ترتیب خراب ہوجاتی ہے۔
