### ISSUE TITLE
Testing Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/MadrassaWeb#35]
Please  make mobile responsive the following pages (Make Changes in your Local Code after getting latest code)

In mobile UI PLease, Hide option of " English  Version"

1) http://darultaqwa.org/Home/Home/
2) http://darultaqwa.org/darul-taqwa-introduction
3) http://darultaqwa.org/darul-taqwa-lectures
4) http://darultaqwa.org/darul-taqwa-books
5) http://darultaqwa.org/darul-taqwa-articles
6) http://darultaqwa.org/Home/ArticlesDetail/10044
7) http://darultaqwa.org/darul-taqwa-contact
8) http://darultaqwa.org/darul-taqwa-gallery
9) http://darultaqwa.org/BooksForDarulTakwaUrdu/MahanamaDarulTakwaUrdu/

**Darult Ifta**

10) http://darultaqwa.org/DarulFtaUrdu/Index/
11) http://darultaqwa.org/DarulFtaUrdu/DarulIftaIntroduction/
12) http://darultaqwa.org/NewAndLatestFatwa/NewAndLatestFatwa/
13) http://darultaqwa.org/Home/LatestFatwaDetail/10071
14) http://darultaqwa.org/AmomoiSawalaat/AmomoiSawalaatList/
15) http://darultaqwa.org/Home/AmomoiSawalaatDetial/10070
16) http://darultaqwa.org/TaksulFika/TaksusFikaPage/
17) http://darultaqwa.org/OpenQuestions/YourQuesionForMainMenu/
18) http://darultaqwa.org/Home/LibraryList/
19) http://darultaqwa.org/FahemiMazameen/FahimeMazameen/
20) http://darultaqwa.org/ContactUs/DarulIftaContactUs/

21) In web.config  add following Key
FacebookURL https://www.facebook.com/jamiadarultaqwa
GoogleURL  https://plus.google.com/117994494550340792119 )
TwitterURL  https://twitter.com/darultaqwaorg
LinkedInURL   www.linkedin.com/in/darultaqwaorg 

and in all layout pages set url of  each social icons from web.config
![image](https://cloud.githubusercontent.com/assets/19146254/26032023/1442f086-38a2-11e7-8688-b8fc8686ab60.png)

and also remove skype icon.

Best option is  create "Uc_SocialLinks" call this user control in all master pages, If possible.

22) for below text create a css and use that css in all pages banner, and use small font size so that it should look much better

![image](https://cloud.githubusercontent.com/assets/19146254/26032033/5ccefef8-38a2-11e7-91fb-c768277a05f1.png)

**Comment by adilshehbaz** [comment]
1) Fixed
2) Fixed
3) Fixed
4) Fixed
5) Fixed
6) Fixed
7) Fixed
8) Fixed
9) Fixed

**Comment by adilshehbaz** [comment]
21) Fixed

**Comment by adilshehbaz** [comment]
10) Fixed

**Comment by adilshehbaz** [comment]
11 to 20) Fixed
