### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/MadrassaWeb#36]

**Comment by serviceproviderpk** [comment]
1) English Version slide show ( taqwa+ifta)
2) In urdu version "Ifta Home page" Slide show is  very small  http://darultaqwa.org/DarulFtaUrdu/Index/
3) On home page web site  (http://darultaqwa.org/)  Title of the book should be in center or  text align right.

**Comment by adilshehbaz** [comment]
1-2 Fixed

**Comment by adilshehbaz** [comment]
3 Fixed

**Comment by adilshehbaz** [comment]
4 Fixed

**Comment by adilshehbaz** [comment]
5-6-7-8-10 Fixed

**Comment by adilshehbaz** [comment]
9 Fixed

**Comment by serviceproviderpk** [comment]
1) On 4 home pages, Side show images size should be same. and  news scrolling should be auto (desktop+mobile UI)
2)  In mobile version "Mahnma List" page not rendering properly do same as for book
![image](https://user-images.githubusercontent.com/19146254/27159372-e8f6df8a-5185-11e7-8eb3-988cc0d9a063.png)
