### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/MadrassaWeb#37]
1) On Jamia  home page , Books title is disturbed
2) On 4 home pages, Slide show images size should be same. and  news scrolling should be auto (desktop+mobile UI)

**Comment by adilshehbaz** [comment]
1-Fixed

**Comment by Darultaqwa** [comment]
•	اردو  ویب سائٹ کے تمام پیجز  کا فونٹ جمیل نوری نستعلیق   سے تبدیل ہوگیا ہے۔ اس کو   جمیل نوری نستعلیق ہی  رہنا چاہیے۔
![100](https://user-images.githubusercontent.com/23413745/27260359-733d5ff6-5443-11e7-8d0f-fac8f2770d80.PNG)
![101](https://user-images.githubusercontent.com/23413745/27260364-9cca243a-5443-11e7-92d2-0efc15d49205.PNG)

•	دارالافتاء و التحقیق  (اردو)کے مین پیج پر سلائیڈ شو کی پکچرز  کے نیچے کا کچھ حصہ نظر نہیں آرہا۔حالانکہ  پکچرز کا سائز بالکل ٹھیک1322،264 ہے۔
http://www.darultaqwa.org/DarulFtaUrdu/Index/
![102](https://user-images.githubusercontent.com/23413745/27260377-0d4cca96-5444-11e7-8f09-f71fb4c4edee.PNG)
![103](https://user-images.githubusercontent.com/23413745/27260389-8249e41e-5444-11e7-9fd2-0cf7a6623734.JPG)

•	دارالافتاء و التحقیق (انگلش) کے مین پیج  کے سلائیڈ شو میں 2 پکچرز لگائی ہیں لیکن نظر صرف 1 آرہی ہے۔ اور پکچرز کے اوپر لنک والی جگہ میں ٹیکسٹ بھی نظر نہیں آرہا۔
http://www.darultaqwa.org/EnglishVersion/DarulIftaEnglish/Index/
![104](https://user-images.githubusercontent.com/23413745/27260407-fdaed36c-5444-11e7-9a8a-ecb55315cb9a.JPG)

•	دارالتقوی اور دارالافتاء و التحقیق کے مین پیج کی چلتی پٹی کی خبریں الگ الگ ہیں۔ جو خبریں دارالتقوی مین پیج کی چلتی پٹی میں لگائی ہیں وہ دارالافتاء و التحقیق مین پیج کی چلتی پٹی میں نظر نہیں آنی چاہئیں۔

•	دارالافتاء و التحقیق کے مین پیج پر نیچے والی سائیڈ بار  میں ’’خاندانی معاملات‘‘ کے نیچے’’مالی معاملات‘‘،’’معاشرت‘‘ اور ’’حلال و حرام‘‘ کو ہونا چاہیے ۔ جیسا کہ پہلے تھا۔ اور اس سائیڈ بار سے  ’’آپکا سوال فارم کے ذریعے ‘‘، ’’نئے اور اہم فتاوی‘‘، اور ’’ عمومی سوالات‘‘ کو ختم کرنا ہے۔اور اس سائیڈ بار کے اوپر ہیڈنگ’’ فہرست فتاوی‘‘ ہونی چاہیے۔
http://www.darultaqwa.org/DarulFtaUrdu/Index/
![105](https://user-images.githubusercontent.com/23413745/27260447-12e09d3c-5446-11e7-8a85-f393b8869f66.JPG)

•	’’آپکے مسائل اور انکا حل‘‘ والے صفحے میں ’’نئے اور اہم فتاوی‘‘ کی جگہ ’’آپکے مسائل اور انکا حل ‘‘ لکھنا ہے اور ’’آپکا سوال فارم کے ذریعے ‘‘، ’’نئے اور اہم فتاوی‘‘، اور ’’ عمومی سوالات‘‘ کو یہاں سے ختم کرنا ہے۔
http://www.darultaqwa.org/Home/msaiCategoriesForLatestFatwa/
![106](https://user-images.githubusercontent.com/23413745/27260480-a71da864-5446-11e7-9b36-48c1c6cb7690.JPG)

•	’’آپکے مسائل اور انکا حل‘‘ والے صفحے میں ’’عقائد و نظریات‘‘، ’’عبادات‘‘، خاندانی معاملات‘‘،’’مالی معاملات‘‘،’’معاشرت‘‘ اور ’’حلال و حرام‘‘ پر کلک کرنے سے فتووں کی ہیڈنگز کھل جاتی ہیں ، ان ہیڈنگز سے پہلے سب کیٹیگری کھلنی چاہیے جیسا کہ دارالافتاء و التحقیق کے  مین پیج پر سائیڈ بار میں سب کیٹیگری کھلتی ہے۔
http://www.darultaqwa.org/Home/msaiCategoriesForLatestFatwa/
![107](https://user-images.githubusercontent.com/23413745/27260498-f57c2080-5446-11e7-94c2-9b34775bda4f.JPG)
![108](https://user-images.githubusercontent.com/23413745/27260509-23580dde-5447-11e7-95a1-343c0c4f8839.JPG)

•	 ریزولوشن 1024، 768 مین پیج دارالتقوی
http://www.darultaqwa.org/Home/Home/
![109](https://user-images.githubusercontent.com/23413745/27260544-4e00d8e4-5448-11e7-8994-91d6202e931b.JPG)

•	ریزولوشن 1024، 768 مین پیج دارالافتاء و التحقیق 
http://www.darultaqwa.org/DarulFtaUrdu/Index/
![110](https://user-images.githubusercontent.com/23413745/27260567-eca03dd2-5448-11e7-900c-87ef98800ae3.JPG)

•	پرنٹ پریویو
http://www.darultaqwa.org/DarulFtaUrdu/Index/
[Darulifta.pdf](https://github.com/serviceproviderpk/MadrassaWeb/files/1083066/Darulifta.pdf)

•	پرنٹ پریویو
http://www.darultaqwa.org/Home/Home/
[Darultaqwa.pdf](https://github.com/serviceproviderpk/MadrassaWeb/files/1083067/Darultaqwa.pdf)

•	موبائل ورژن میں خبریں رائٹ سے لیفٹ کی بجائے لیفٹ سے رائٹ سائیڈ پر جانی چاہئیں۔تاکہ خبریں پڑھی جاسکیں۔
![111](https://user-images.githubusercontent.com/23413745/27260626-2f91e2a2-544a-11e7-990e-c0a550d4b85a.JPG)

**Comment by serviceproviderpk** [comment]
Fixed all issues.
