### ISSUE TITLE
برائے مہربانی یہ بھی بتادیں کہ دارالافتاء ویب سائٹ  پر ’’آپکا سوال فارم‘‘  کے ذریعے سوال پوچھنے والوں کے ای میل ایڈریس کیسے پتہ چلیں گے؟

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/MadrassaWeb#39]
برائے مہربانی یہ بھی بتادیں کہ
دارالافتاء ویب سائٹ  پر ’’آپکا سوال فارم‘‘  کے ذریعے سوال پوچھنے والوں کے ای میل ایڈریس کیسے پتہ چلیں گے؟

**Comment by serviceproviderpk** [comment]
Login  to Dashboard
select Subscriber  
Contact us

is page sari information ho gi ager user "Apka swala" ya contact us say request kray.

uska Name,Email,Phone, description

**Comment by Darultaqwa** [comment]
آپکا سوال فارم کے ذریعے سوال بھیجنے والوں کی کوئی معلومات ’’کانٹیکٹ اس‘‘ میں موجود نہیں ہے۔ حالانکہ  لوگوں نے سوال پوچھے ہوئے ہیں۔
![contact us](https://user-images.githubusercontent.com/23413745/27848220-ebbdbf36-615c-11e7-88fa-5c7bc3fd49b6.JPG)
![questions](https://user-images.githubusercontent.com/23413745/27848224-f32021f6-615c-11e7-81c7-07d400c260ee.JPG)

**Comment by serviceproviderpk** [comment]
Login  to Dashboard
Question section

Fixed
