### ISSUE TITLE
UI- Feedback Internal

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/MadrassaWeb#41]
1- In Darul Ifta books slide show "Book Title " is Trimed from right side instead of left side, I i think it RTL issue

![image](https://user-images.githubusercontent.com/19146254/28397093-df01d26a-6d18-11e7-84d3-8a893e143495.png)

you can fix it by adding RTL

![image](https://user-images.githubusercontent.com/19146254/28397174-5b0b2154-6d19-11e7-9c91-2f93ff02352d.png)

I suggest  re-add "rtl" in body tag and overwrite it in page where it is required..

and book title should be also clickable.

2. Please improve Beyaan list page and try to do it just like  below
![image](https://user-images.githubusercontent.com/19146254/28397355-8d85680a-6d1a-11e7-8bbd-3ecd11edba6b.png)
and also please check it in Mobile UI>

3. on Edit Book, Photo issue. if we change only title, It's photo is set as default photo (no photo) image.
4. Fatwa receipt with proper data ,Fatwa flow testing with different Assignments/document history etc

test and discuss if any confusion as they provided documents.
5. If user type is not admin in left menu hide other menu  like "Categories" and Fatwa Manuall.
Only link will be visible "Manage Fatwa" there will  no sub menu items.

only user type admin and composer should be able to "Add" Fatwa for other users hide "Add button"

Thanks,
Asif

**Comment by adilshehbaz** [comment]
1-Fixed
